apiVersion: v1
kind: Pod
metadata:
  name: iot3011
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.11\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3011
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_01.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_23_humidity.txt data/Output/Network_03/iot_01.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3012
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.12\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3012
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_02.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_23_voltage.txt data/Output/Network_03/iot_02.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3013
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.13\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3013
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_03.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_23_temperature.txt data/Output/Network_03/iot_03.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3014
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.14\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3014
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_04.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_23_light.txt data/Output/Network_03/iot_04.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3015
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.15\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3015
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_05.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_21_humidity.txt data/Output/Network_03/iot_05.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3016
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.16\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3016
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_06.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_21_voltage.txt data/Output/Network_03/iot_06.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3017
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.17\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3017
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_07.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_21_temperature.txt data/Output/Network_03/iot_07.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3018
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.18\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3018
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_08.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_21_light.txt data/Output/Network_03/iot_08.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3019
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.19\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3019
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_09.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_47_humidity.txt data/Output/Network_03/iot_09.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3020
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.20\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3020
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_10.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_47_voltage.txt data/Output/Network_03/iot_10.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3021
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.21\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3021
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_11.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_47_temperature.txt data/Output/Network_03/iot_11.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3022
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.22\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3022
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_12.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_47_light.txt data/Output/Network_03/iot_12.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3023
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.23\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3023
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_13.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_46_humidity.txt data/Output/Network_03/iot_13.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3024
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.24\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3024
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_14.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_46_voltage.txt data/Output/Network_03/iot_14.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
---
apiVersion: v1
kind: Pod
metadata:
  name: iot3025
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.25\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: iot3025
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: iot:wp3.v2
    command: ['bash', '-c', ' sleep 30 && tcpdump -w data/Output/Network_03/iot_15.pcap & ./IntelLabData2004.py 10.128.30.30 2000 data/Input/mote_46_temperature.txt data/Output/Network_03/iot_15.txt && tail -f /dev/null']
  nodeSelector:
    rede: '9'
