apiVersion: v1
kind: Pod
metadata:
  name: server
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.10.30\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: smd1
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: smd-metrica:wp3.v5
    command: ['sh', '-c', 'tcpdump -w data/Output/Server/Server_01/server1_$(date +"%H%M%S").pcap & ./smd Server_01/ 50001 50002 4 10.128.20.30 10.128.30.30 10.128.40.30 10.128.50.30']
    ports:
      - containerPort: 50001
        protocol: UDP
        name: porta-1
    ports:
      - containerPort: 50002
        protocol: TCP
        name: porta-2
    resources:
      limits:
        memory: "3Mi"
        cpu: "5m"
  nodeSelector:
    rede: '2'
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server2
  name: server2
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.20.30\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: smd2
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: smd-metrica:wp3.v5
    command: ['sh', '-c', 'tcpdump -w data/Output/Server/Server_02/server2_$(date +"%H%M%S").pcap & ./smd Server_02/ 50001 50002 4 10.128.10.30 10.128.30.30 10.128.40.30 10.128.50.30']
    ports:
      - containerPort: 50001
        protocol: UDP
        name: porta-1
    ports:
      - containerPort: 50002
        protocol: TCP
        name: porta-2
    resources:
      limits:
        memory: "3Mi"
        cpu: "5m"
  nodeSelector:
    rede: "5"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server3
  name: server3
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.30.30\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: smd3
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: smd-metrica:wp3.v5
    command: ['sh', '-c', 'tcpdump -w /app/data/Output/Server/Server_03/server3_$(date +"%H%M%S").pcap & ./smd Server_03/ 50001 50002 4 10.128.10.30 10.128.20.30 10.128.40.30 10.128.50.30']
    ports:
      - containerPort: 50001
        protocol: UDP
        name: porta-1
    ports:
      - containerPort: 50002
        protocol: TCP
        name: porta-2
    resources:
      limits:
        memory: "3Mi"
        cpu: "5m"
  nodeSelector:
    rede: "8"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server4
  name: server4
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.40.30\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: smd4
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: smd-metrica:wp3.v5
    command: ['sh', '-c', 'tcpdump -w /app/data/Output/Server/Server_04/server4_$(date +"%H%M%S").pcap & ./smd Server_04/ 50001 50002 4 10.128.10.30 10.128.20.30 10.128.30.30 10.128.50.30']
    ports:
      - containerPort: 50001
        protocol: UDP
        name: porta-1
    ports:
      - containerPort: 50002
        protocol: TCP
        name: porta-2
    resources:
      limits:
        memory: "3Mi"
        cpu: "5m"
  nodeSelector:
    rede: "11"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server5
  name: server5
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.128.50.30\"]"
spec:
  volumes:
  - name: vol
    hostPath:
      path: /vol
  containers:
  - name: smd5
    volumeMounts:
      - name: vol
        mountPath: /app/data  # in the container filesystem
    image: smd-metrica:wp3.v5
    command: ['sh', '-c', 'tcpdump -w /app/data/Output/Server/Server_05/server5_$(date +"%H%M%S").pcap & ./smd Server_05/ 50001 50002 4 10.128.10.30 10.128.20.30 10.128.30.30 10.128.40.30']
    ports:
      - containerPort: 50001
        protocol: UDP
        name: porta-1
    ports:
      - containerPort: 50002
        protocol: TCP
        name: porta-2
    resources:
      limits:
        memory: "3Mi"
        cpu: "5m"
  nodeSelector:
    rede: "14"

